#!/bin/bash
DNSFILE="/home/dfoulks/asf/infrastructure-trunk/dns/zones/inventory.conf"
ZONEFILE="/home/dfoulks/asf/infrastructure-trunk/dns/zones/apache.org"
if [ ! $1 ]; then echo "no host or action provided" && exit 1; fi

# == Warwalrux' Hammerscript ==
#   "Every tool's a hammer"
#       - Adam Savage
#
# --- the common infra functions this script streamlines ---
#
# - Super SSH (asf999)
#       asf super hostname
#
if [[ "$1" == "super" ]]; then
	host="$2.apache.org"
	ssh asf999@$host

# - Generate a password
#        asf genpw
#
elif [[ "$1" == "genpw" ]]; then
	openssl rand -base64 20

# - Pull files
#       asf pull host src dest
#
elif [[ "$1" == "pull" ]]; then
	host="$2.apache.org"
	src=$3
	dest=$4
    rsync -rv --rsync-path="sudo rsync" $host:$src $dest

# - Push files
#       asf push src host dest
#
elif [[ "$1" == "push" ]]; then
	src=$2
	host="$3.apache.org"
	dest=$4
    rsync -rv --rsync-path="sudo rsync" $src $host:$dest

# - Ping an apache.org host
#       asf ping host
#
elif [[ "$1" == "ping" ]]; then
	host=$2
	ping $2.apache.org

# - check apache DNS for an apache.org host
#       asf what host
#
elif [[ "$1" == "what" ]]; then
	host=$2
	echo "--- $DNSFILE ---" 
	grep $2 $DNSFILE
	
	echo -e "\n--- $ZONEFILE ---" 
	grep $2 $ZONEFILE
# - SSH to a ygridcore node
#       asf node $xx // asf9$xx
#
elif [[ "$1" == "node" ]]; then
	hostname="asf9$2.gq1.ygridcore.net"
	ssh $hostname

# - Print Help
#       asf help
#
elif [[ "$1" == "help" ]]; then
	grep '^#' $0 | grep -v 'bash' | sed -e 's/#/  /g'

# - Print manifest of asf hosts
#   which is a yaml formatted list of asf hosts
#       asf list
#
elif [[ "$1" == "list" ]]; then
    /usr/bin/svn cat https://svn.apache.org/repos/infra/infrastructure/trunk/dns/zones/inventory.yaml
# - SSH to an apache.org host
#       asf host
#
else
	hostname="$1.apache.org"
	ssh -A $hostname
fi
