#!/bin/bash
DNSFILE="/home/dfoulks/asf/infrastructure-trunk/dns/zones/generate.py"
if [ ! $1 ]; then echo "no host or action provided" && exit 1; fi

# == The Worst Tool Ever ==
#   "it's like hammer, but not as useful!"
#       - warwalrux
#
# --- the common infra functions this script streamlines ---
#
# - Super SSH (asf999)
#       asf super hostname
#
if [[ "$1" == "super" ]]; then
	host="$2.apache.org"
	ssh asf999@$host

# - Generate a password
#        asf genpw
#
elif [[ "$1" == "genpw" ]]; then
	openssl rand -base64 20

# - Pull files
#       asf pull host src dest
#
elif [[ "$1" == "pull" ]]; then
	host="$2.apache.org"
	src=$3
	dest=$4
	scp dfoulks@$host:$src $dest

# - Push files
#       asf push src host dest
#
elif [[ "$1" == "push" ]]; then
	src=$2
	host="$3.apache.org"
	dest=$4
	scp $src dfoulks@$host:/$dest

# - Ping an apache.org host
#       asf ping host
#
elif [[ "$1" == "ping" ]]; then
	host=$2
	ping $2.apache.org

# - check apache DNS for an apache.org host
#       asf what host
#
elif [[ "$1" == "what" ]]; then
	host=$2
	grep $2 $DNSFILE
# - SSH to a ygridcore node
#       asf node $xx // asf9$xx
#
elif [[ "$1" == "node" ]]; then
	hostname="asf9$2.gq1.ygridcore.net"
	ssh $hostname

# - Print Help
#       asf help
#
elif [[ "$1" == "help" ]]; then
	grep '^#' $0 | grep -v 'bash' | sed -e 's/#/  /g'

# - Print asf hosts from ~/.asfhosts
#   which is a text list of asf hosts
#       asf list
#
elif [[ "$1" == "list" ]]; then
	less ~/bin/.asfhosts

# - SSH to an apache.org host
#       asf host
#
else
	hostname="$1.apache.org"
	ssh -A $hostname
fi
