#!/usr/bin/python3

import argparse
import ast
import jinja2
import json
import pprint

pp = pprint.PrettyPrinter()

parser = argparse.ArgumentParser()
parser.add_argument('-f', '--file', help="input file")

printer = parser.add_mutually_exclusive_group(required=True)
printer.add_argument('-J', '--jinja', help="Jinja Template string")
printer.add_argument('-P', '--pretty', action='store_true', help="Pretty Print string")

loader = parser.add_mutually_exclusive_group(required=True)
loader.add_argument('-a', '--ast', action='store_true', help="Use AST Parser")
loader.add_argument('-j', '--json', action='store_true', help="Use JSON parser")

args = parser.parse_args()

data = open(args.file, 'r')

# Parse the file with the chosen Loader method
if args.ast: 
    results = ast.literal_eval(data.read())
elif args.json:
    results = json.loads(data.read().replace("\'", "\""))

# Output the file using the preferred output method
if args.jinja:
    template = jinja2.Template(args.jinja)
    print(template.render(results=results))
else:
    pp.pprint(results)
