#!/bin/bash
launchpad="/home/$USER/asf"
hieraeyaml=false

function edit_secure() {
    path=`readlink -f $1`
    if [[ "$(echo $path | grep -q "infrastructure-p6" && echo $?)" == "0" ]]; then
        recips_file="$launchpad/infrastructure-p6/data/hiera-eyaml-gpg.recipients"
        hieraeyaml=true
    else
        echo "You're not in a repository I recognize"
        exit 0
    fi
    if [ $hieraeyaml ]; then
        eyaml edit -t -v -n gpg --gpg-always-trust --gpg-recipients-file $recips_file $path
    else
        echo "No encryption alternatives set"
    fi
}

edit_secure $1
