#!/usr/bin/python3 -B
import argparse
import base64
import requests
import json
import sys
import time
import pprint
import jinja2

url="https://issues.apache.org/jira/rest/api/latest"
pp = pprint.PrettyPrinter()

def getOpts():
    parser = argparse.ArgumentParser(description='github api caller')
    parser.add_argument('-t', '--tokenfile', required=True, help="tokenfile")

    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument('-g', '--get', help="Jira API Get + Query string")
    action.add_argument('-p', '--post', help="Jira API Put + Query string")
    action.add_argument('-u', '--put', help="Jira API Put + Query string")
    action.add_argument('-d', '--delete', help="Jira API Put + Query string")
    
    output = parser.add_mutually_exclusive_group()
    output.add_argument('-J', '--j2', help="jinja2 formatting string")
    output.add_argument('-O', '--outfile', help="dump raw data to file")
    output.add_argument('-F', '--formatted', action="store_true", help="Pretty Print data")
    args = parser.parse_args()

    return args

def main () :
    args = getOpts()
    
    # Check token stuffs
    token = open(args.tokenfile).read().strip()

    s = requests.Session()
    # tokenstring = "%s:%s" % (args.login, token)
    # b_token = bytes(tokenstring, 'utf-8')
    authheader = "Bearer " + token
    headers = {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "Authorization": authheader,
    }
    s.headers.update(headers)

    if args.get:
        results = s.get("%s/%s"%(url, args.get)).json()
    if args.post:
        results = s.put("%s/%s"%(url, args.post)).json()
    if args.put:
        results = s.put("%s/%s"%(url, args.put)).json()
    if args.delete:
        results = s.put("%s/%s"%(url, args.delete)).json()

    if args.outfile:
        json.dump(results, open(args.outfile, "w+"))
    else:
        if args.j2:
            t = jinja2.Template(args.j2)
            print(t.render(result=result))
        elif args.formatted:
            pp.pprint(results)
        else:
            print(results)


if __name__ == "__main__":
    main()
