#!/usr/bin/env python3
""" Inline Reverse DNS Looker-upper-ator-inator """
import socket
import sys
import re


def is_ip(ip_addr):
    """
    :type IP: str
    :rtype: str
    """

    def is_ipv4(check_val):
        """ Check to see if ip string is ipv4 """
        try:
            return str(int(check_val)) == check_val and 0 <= int(check_val) <= 255
        except:
            return False

    def is_ipv6(check_val):
        """ Check to see if ip string is ipv6 """
        if len(check_val) > 4:
            return False
        try:
            return int(check_val, 16) >= 0 and check_val[0] != "-"
        except:
            return False

    if ip_addr.count(".") == 3 and all(is_ipv4(i) for i in ip_addr.split(".")):
        return "ipv4"
    if ip_addr.count(":") == 7 and all(is_ipv6(i) for i in ip_addr.split(":")):
        return "ipv6"
    return False


for line in sys.stdin.readlines():
    aa = re.findall(r"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}", line)
    if aa:
        for match in aa:
            if str(is_ip(match)) == "ipv4" or str(is_ip(match)) == "ipv6":
                try:
                    hostname = socket.gethostbyaddr(match)[0]
                except socket.herror:
                    hostname = "UNKNOWN"
                line = line.replace(match, match + " (" + hostname + ") ")
        print(line, end="")
    else:
        print(line, end="")
