#!/usr/bin/env python3

import socket
import sys
import re


class CheckIP(object):
    def is_ip(self, IP):
        """
      :type IP: str
      :rtype: str
      """

        def is_ipv4(s):
            try:
                return str(int(s)) == s and 0 <= int(s) <= 255
            except:
                return False

        def is_ipv6(s):
            if len(s) > 4:
                return False
            try:
                return int(s, 16) >= 0 and s[0] != "-"
            except:
                return False

        if IP.count(".") == 3 and all(is_ipv4(i) for i in IP.split(".")):
            return "ipv4"
        if IP.count(":") == 7 and all(is_ipv6(i) for i in IP.split(":")):
            return "ipv6"
        return False


ch = CheckIP()
# priint(socket.gethostbyaddr('95.216.26.30')[0])
for line in sys.stdin.readlines():
    aa = re.findall(r"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}", line)
    if aa:
        for match in aa:
            if str(ch.is_ip(match)) == "ipv4" or str(ch.is_ip(match)) == "ipv6":
                try:
                    hostname = socket.gethostbyaddr(match)[0]
                except socket.herror:
                    hostname = "UNKNOWN"
                line = line.replace(match, match + " (" + hostname + ") ")
        print(line, end="")
    else:
        print(line, end="")
